require 'scaffold_parser/templates/utils'
require 'scaffold_parser/templates/base_method'
require 'scaffold_parser/templates/at_method'
require 'scaffold_parser/templates/klass'
require 'scaffold_parser/templates/list_method'
require 'scaffold_parser/templates/proxy_list_method'
require 'scaffold_parser/templates/submodel_method'
